<?php

/**
 * @file
 * Copyright 2018 Google Inc.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_type_alter().
 */
function apigee_m10n_teams_entity_type_alter(array &$entity_types) {
  apigee_m10n_teams_service()->entityTypeAlter($entity_types);
}

/**
 * Helper to get the teams service.
 *
 * This uses static caching for performance rather than to maintain a singleton.
 * The container handles singleton instantiation. As for performance, see:
 * `\Symfony\Component\DependencyInjection\Container::get()`.
 *
 * @return \Drupal\apigee_m10n_teams\MonetizationTeamsInterface
 *   The `apigee_m10n.teams` service.
 */
function apigee_m10n_teams_service() {
  static $service;

  if (!isset($service)) {
    $service = \Drupal::service('apigee_m10n.teams');
  }

  return $service;
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function apigee_m10n_teams_package_access(EntityInterface $entity, $operation, AccountInterface $account) {
  return apigee_m10n_teams_service()->entityAccess($entity, $operation, $account);
}
