apigee_m10n_add_credit.config:
  type: config_object
  label: 'Apigee add credit config'
  mapping:
    mail_on_error:
      type: boolean
      label: 'Whether or not to sent an email if there is an error applying a recharge.'
    error_recipient:
      type: string
      label: 'The email address to send errors to.'

commerce_product.commerce_product_type.*.third_party.apigee_m10n_add_credit:
  type: mapping
  label: 'Apigee add credit'
  mapping:
    apigee_m10n_enable_add_credit:
      type: boolean
      label: 'Whether to enable "Add credit" for this product.'
