apigee_m10n_add_credit.config:
  type: config_object
  label: 'Apigee add credit config'
  mapping:
    notify_on:
      type: string
      label: 'Whether to sent notifications "always" or "error_only".'
    notification_recipient:
      type: string
      label: 'The email address to send notifications to.'

commerce_product.commerce_product_type.*.third_party.apigee_m10n_add_credit:
  type: mapping
  label: 'Apigee add credit'
  mapping:
    apigee_m10n_enable_add_credit:
      type: boolean
      label: 'Whether to enable "Add credit" for this product.'
    apigee_m10n_enable_skip_cart:
      type: boolean
      label: 'Where to skip cart for this product'

field.value.apigee_top_up_amount:
  type: mapping
  label: 'Top up amount'
  mapping:
    mininum:
      type: string
      label: 'Minimum'
    maximum:
      type: string
      label: 'Maximum'
    number:
      type: string
      label: 'Number'
    currencyCode:
      type: string
      label: 'Currency code'

field.field_settings.apigee_top_up_amount:
  type: mapping
  label: 'Top up amount settings'
  mapping:
    available_currencies:
      type: sequence
      label: 'Available currencies'
      orderby: value
      sequence:
        type: string
