<?php

/**
 * @file
 * Copyright 2018 Google Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function apigee_m10n_api_product_access(EntityInterface $entity, $operation, AccountInterface $account) {
  // For the assignment operation a product must either be free or purchased.
  if ($operation == 'assign') {
    return \Drupal::service('apigee_m10n.monetization')
      ->apiProductAssignmentAccess($entity, $account);
  }

  // No opinion on other operations.
  return AccessResult::neutral();
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function apigee_m10n_theme_suggestions_rate_plan(array $variables) {
  $suggestions = [];
  $rate_plan = $variables['elements']['#rate_plan'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'apigee_rate_plan__' . $sanitized_view_mode;
  $suggestions[] = 'apigee_rate_plan__' . $rate_plan->bundle();
  $suggestions[] = 'apigee_rate_plan__' . $rate_plan->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'apigee_rate_plan__' . $rate_plan->id();
  $suggestions[] = 'apigee_rate_plan__' . $rate_plan->id() . '__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Prepares variables for rate-plan templates.
 *
 * Default template: rate-plan.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - rate_plan: The Apigee  package rate plan entity.
 *   - view_mode: View mode; e.g., 'full', 'teaser', etc.
 *   - url: The canonical URL to view the plan directly.
 *
 * @throws \Drupal\Core\Entity\EntityMalformedException
 */
function template_preprocess_rate_plan(&$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];

  $variables['rate_plan'] = $variables['elements']['#rate_plan'];
  /** @var \Drupal\apigee_m10n\Entity\RatePlanInterface $rate_plan */
  $rate_plan = $variables['rate_plan'];

  $variables['url'] = $rate_plan->toUrl('canonical', [
    'language' => $rate_plan->language(),
  ]);
}

/**
 * Implements hook_theme().
 */
function apigee_m10n_theme($existing, $type, $theme, $path) {
  return [
    'rate_plan' => [
      'render element' => 'elements',
    ],
    'prepaid_balances' => [
      'variables' => ['balances' => NULL],
      'template' => 'prepaid-balances',
    ],
    'package_list' => [
      'variables' => ['package_list' => NULL, 'plan_list' => NULL],
      'template' => 'package-list',
    ],
    'package' => [
      'variables' => [
        'package' => NULL,
        'product_list' => NULL,
        'plan_list' => NULL,
      ],
      'template' => 'package',
    ],
    'product_list' => [
      'variables' => ['product_list' => NULL],
    ],
    'api_product' => [
      'variables' => ['api_product' => NULL],
    ],
    'rate_plan_detail' => [
      'variables' => ['detail' => NULL],
      'template' => 'rate-plan-detail',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function apigee_m10n_preprocess_package_list(&$variables) {
  // Convert the package list into individual renderable items.
  array_walk($variables['package_list'], function (&$package) use ($variables) {
    $package = [
      '#theme' => 'package',
      '#package' => $package,
      '#plan_list' => $variables['plan_list'][$package->id()],
    ];
  });
}

/**
 * Implements hook_preprocess_HOOK().
 */
function apigee_m10n_preprocess_package(&$variables) {
  /** @var \Apigee\Edge\Api\Monetization\Entity\ApiProduct[] $products */
  // Convert apigee monetization products to product entities.
  $variables['product_list'] = [
    '#theme' => 'product_list',
    '#product_list' => $variables['package']->getApiProducts(),
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function apigee_m10n_preprocess_product_list(&$variables) {
  // Convert the package list into individual renderable items.
  array_walk($variables['product_list'], function (&$api_product) {
    $api_product = [
      '#theme' => 'api_product',
      '#api_product' => $api_product,
    ];
  });
}
