<?php

/**
 * @file
 * Copyright 2018 Google Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function apigee_m10n_api_product_access(EntityInterface $entity, $operation, AccountInterface $account) {
  // For the assignment operation a product must either be free or purchased.
  if ($operation == 'assign') {
    return \Drupal::service('apigee_m10n.monetization')
      ->apiProductAssignmentAccess($entity, $account);
  }

  // No opinion on other operations.
  return AccessResult::neutral();
}

/**
 * Implements hook_theme().
 */
function apigee_m10n_theme($existing, $type, $theme, $path) {
  return [
    'apigee_entity__rate_plan' => [
      'base hook' => 'apigee_entity',
    ],
    'apigee_entity__package' => [
      'base hook' => 'apigee_entity',
    ],
    'api_product' => [
      'variables' => ['api_product' => NULL],
    ],
    'rate_plan_detail' => [
      'variables' => ['detail' => NULL],
      'template' => 'rate-plan-detail',
    ],
    'conflicting_products' => [
      'variables' => ['items' => NULL],
      'template' => 'conflicting-products',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function apigee_m10n_form_user_admin_permissions_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('apigee_m10n.monetization')->formUserAdminPermissionsAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function apigee_m10n_user_role_presave(EntityInterface $entity) {
  \Drupal::service('apigee_m10n.monetization')->userRolePresave($entity);
}
