apigee_m10n.rate_plan.config:
  type: config_object
  label: 'Rate plan settings'
  mapping:
    catalog_view_mode:
      type: string
      label: 'View mode to use for rate plans on the "Pricing and plans" page.'

apigee_m10n.prepaid_balance.config:
  type: config_object
  label: 'Prepaid balance settings'
  mapping:
    cache:
      type: mapping
      mapping:
        max_age:
          type: integer
          label: 'Max age for prepaid balance'
    enable_insufficient_funds_workflow:
      type: boolean
      label: 'Whether to enable insufficient funds workflow'

apigee_m10n.purchased_plan.config:
  type: config_object
  label: 'Rate plan purchase settings'
  mapping:
    purchase_label:
      type: label
      label: 'The purchase label.'
    purchase_form_title:
      type: label
      label: 'Purchase form page title.'
    purchase_button_label:
      type: label
      label: 'Purchase button label.'
    cancel_question:
      type: label
      label: 'Cancel purchased plan form page title.'
    cancel_description:
      type: label
      label: 'Cancel purchased plan form description.'
    cancel_button_label:
      type: label
      label: 'Cancel purchased plan button label.'
    already_purchased_label:
      type: label
      label: 'Already purchased title.'

field.formatter.settings.apigee_purchase_plan_link:
  type: mapping
  label: 'Purchase plan link'
  mapping:
    label:
      type: label
      label: 'Purchase label'

field.formatter.settings.apigee_purchase_plan_form:
  type: mapping
  label: 'Rate plan purchase form settings'
  mapping:
    label:
      type: label
      label: 'Purchase Label'

field.formatter.settings.apigee_datestamp:
  type: mapping
  label: 'Apigee Edge date'
  mapping:
    date_format:
      type: string
      label: 'Date format'
    custom_date_format:
      type: string
      label: 'Custom date format'
    timezone:
      type: string
      label: 'Timezone'

field.formatter.settings.apigee_tnc_default:
  type: mapping
  label: 'Terms and Conditions'
  mapping:
    default_description:
      type: string
      label: 'Terms and Conditions'
