apigee_m10n.rate_plan.config:
  type: config_object
  label: 'Rate plan settings'
  mapping:
    catalog_view_mode:
      type: string
      label: 'View mode to use for rate plans on the "Pricing and plans" page.'

apigee_m10n.prepaid_balance.config:
  type: config_object
  label: 'Prepaid balance settings'
  mapping:
    cache:
      type: mapping
      mapping:
        max_age:
          type: integer
          label: 'Max age for prepaid balance'
    enable_insufficient_funds_workflow:
      type: boolean
      label: 'Whether to enable insufficient funds workflow'

apigee_m10n.subscription.config:
  type: config_object
  label: 'Rate plan purchase settings'
  mapping:
    subscribe_label:
      type: label
      label: 'The subscribe label.'
    subscribe_form_title:
      type: label
      label: 'Subscribe form page title.'
    subscribe_button_label:
      type: label
      label: 'Subscribe button label.'
    unsubscribe_question:
      type: label
      label: 'Unsubscribe form page title.'
    unsubscribe_description:
      type: label
      label: 'Unsubscribe form description.'
    unsubscribe_button_label:
      type: label
      label: 'Unsubscribe button label.'
    already_purchased_label:
      type: label
      label: 'Already subscribed title.'

field.formatter.settings.apigee_subscribe_link:
  type: mapping
  label: 'Subscribe Link'
  mapping:
    label:
      type: label
      label: 'Subscribe label'

field.formatter.settings.apigee_subscribe_form:
  type: mapping
  label: 'Subscribe form settings'
  mapping:
    label:
      type: label
      label: 'Subscribe Label'

field.formatter.settings.apigee_datestamp:
  type: mapping
  label: 'Apigee Edge date'
  mapping:
    date_format:
      type: string
      label: 'Date format'
    custom_date_format:
      type: string
      label: 'Custom date format'
    timezone:
      type: string
      label: 'Timezone'

field.formatter.settings.apigee_tnc_default:
  type: mapping
  label: 'Terms and Conditions'
  mapping:
    default_description:
      type: string
      label: 'Terms and Conditions'
