apigee_m10n.rate_plan.config:
  type: config_object
  label: 'Rate plan settings'
  mapping:
    catalog_view_mode:
      type: string
      label: 'View mode to use for rate plans on the "Pricing and plans" page.'

apigee_m10n.prepaid_balance.config:
  type: config_object
  label: 'Prepaid balance settings'
  mapping:
    cache:
      type: mapping
      mapping:
        max_age:
          type: integer
          label: 'Max age for prepaid balance'
    enable_insufficient_funds_workflow:
      type: boolean
      label: 'Whether to enable insufficient funds workflow'
    max_statement_history_months:
      type: integer
      label: 'How many months in the past to allow billing statements to be generated.'

field.value.apigee_price:
  type: mapping
  label: 'Price'
  mapping:
    amount:
      type: decimal
      label: 'Amount'
    currency_code:
      type: string
      label: 'Currency code'

field.formatter.settings.apigee_price:
  type: mapping
  label: 'Default price formatter settings'
  mapping:
    strip_trailing_zeroes:
      type: boolean
      label: 'Strip trailing zeroes after the decimal point'
    currency_display:
      type: string
      label: 'Currency display'

field.formatter.settings.apigee_purchase_plan_link:
  type: mapping
  label: 'Purchase plan link'
  mapping:
    label:
      type: label
      label: 'Purchase label'

field.formatter.settings.apigee_purchase_plan_form:
  type: mapping
  label: 'Rate plan purchase form settings'
  mapping:
    label:
      type: label
      label: 'Purchase Label'

field.formatter.settings.apigee_datestamp:
  type: mapping
  label: 'Apigee Edge date'
  mapping:
    date_format:
      type: string
      label: 'Date format'
    custom_date_format:
      type: string
      label: 'Custom date format'
    timezone:
      type: string
      label: 'Timezone'

field.formatter.settings.apigee_tnc_default:
  type: mapping
  label: 'Terms and Conditions'
  mapping:
    default_description:
      type: string
      label: 'Terms and Conditions'

field.formatter.settings.apigee_date_and_text_formatter:
  type: mapping
  label: 'Apigee date and text formatter'
  mapping:
    date_format:
      type: string
      label: 'Date format'
    custom_date_format:
      type: string
      label: 'Custom date format'
    timezone:
      type: string
      label: 'Timezone'
    text:
      type: string
      label: 'Text'
