apigee_m10n.rate_plan.config:
  type: config_object
  label: 'Rate plan settings'
  mapping:
    product_rate_plan_view_mode:
      type: string
      label: 'View mode to use when viewing rate plans within packages.'

apigee_m10n.subscription.config:
  type: config_object
  label: 'Subscription settings'
  mapping:
    subscribe_form_title:
      type: string
      label: 'Subscribe form page title.'
    subscribe_button_label:
      type: string
      label: 'Subscribe button label.'


field.formatter.settings.apigee_subscribe_link:
  type: mapping
  label: 'Subscribe Link'
  mapping:
    subscribe_label:
      type: string
      label: 'Subscribe label'
