apigee_m10n.rate_plan.config:
  type: config_object
  label: 'Rate plan settings'
  mapping:
    product_rate_plan_view_mode:
      type: string
      label: 'View mode to use when viewing rate plans within packages.'

apigee_m10n.subscription.config:
  type: config_object
  label: 'Subscription settings'

field.formatter.settings.apigee_subscribe_link:
  type: mapping
  label: 'Element type'
  mapping:
    element_type:
      type: string
      label: 'Element type'
