commerce_product.commerce_product_type.*.third_party.apigee_m10n_top_up:
  type: mapping
  label: 'Apigee Top Up'
  mapping:
    apigee_m10n_enable_top_up:
      type: boolean
      label: 'Whether to enable top up for this product.'
