apigee_m10n_top_up.config:
  type: config_object
  label: 'Apigee Top Up'
  mapping:
    mail_on_error:
      type: boolean
      label: 'Whether or not to sent an email if there is an error applying a recharge.'
    error_recipient:
      type: string
      label: 'The email address to send errors to.'

commerce_product.commerce_product_type.*.third_party.apigee_m10n_top_up:
  type: mapping
  label: 'Apigee Top Up'
  mapping:
    apigee_m10n_enable_top_up:
      type: boolean
      label: 'Whether to enable top up for this product.'
