<?php
/**
 * @file
 * Copyright 2018 Google Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\commerce_product\Entity\ProductType;


/**
 * Implements hook_mail().
 */
function apigee_m10n_add_credit_mail($key, &$message, $params) {
  switch($key) {
    case 'balance_adjustment_error_report':
      $options = ['langcode' => $message['langcode']];
      $params['@site'] = \Drupal::config('system.site')->get('name');
      $message['subject'] = t('Developer account add credit error from @site', $params, $options);
      $message['body'][0] = t("There was an error applying a credit to an account. \n\r\n\r" . $params['report_text'] . "\n\r\n\r@error", $params, $options);
      break;
  }
}

/**
 * When an order item is created, we need to check to see if the product is an
 * add credit item. If it is, we should store a reference to the developer that
 * we are topping up so it can be used to credit the appropriate account.
 *
 * Implements hook_ENTITY_TYPE_create().
 */
function apigee_m10n_add_credit_commerce_order_item_create(\Drupal\Core\Entity\EntityInterface $entity) {
  /** @var \Drupal\commerce_order\Entity\OrderItemInterface $entity */
  /** @var \Drupal\commerce_product\Entity\ProductVariationInterface $variant */
  // Check to see if an "Add credit" product is what's being added.
  if ($entity instanceof \Drupal\commerce_order\Entity\OrderItemInterface
    && ($variant = $entity->getPurchasedEntity())
    && ($product = $variant->getProduct())
    && !empty($product->apigee_add_credit_enabled->value)
  ) {
    // Save the current user as the top up recipient. We might need to change
    // how this works when topping up a company or a non-current user.
    $entity->setData('add_credit_account', \Drupal::currentUser()->getEmail());
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function apigee_m10n_add_credit_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'commerce_product') {
    // The base field needs to be added to all product types for the storage to be
    // allocated but the option to enable will be hidden and unused unless enabled
    // for that bundle.
    $fields['apigee_add_credit_enabled'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('This is an Apigee add credit product'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDefaultValue(FALSE);

    return $fields;
  }
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function apigee_m10n_add_credit_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  // Make sure we are dealing with a product bundle that has Apigee add credit enabled.
  if ($entity_type->id() === 'commerce_product'
    && ($prooduct_type = ProductType::load($bundle))
    && $prooduct_type->getThirdPartySetting('apigee_m10n_add_credit', 'apigee_m10n_enable_add_credit')
  ) {
    // Apigee add credit enabled products will automatically update a developer's
    // balance upon payment completion. This adds a base field to the bundle to
    // allow add credit to be enabled for products of the bundle individually.
    $add_credit_base_def = clone $base_field_definitions['apigee_add_credit_enabled'];
    $add_credit_base_def
      ->setDefaultValue(TRUE)
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayOptions('form', ['weight' => 25])
      ->setDisplayConfigurable('view', TRUE);
    return ['apigee_add_credit_enabled' => $add_credit_base_def];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function apigee_m10n_add_credit_form_commerce_product_type_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  apigee_m10n_add_credit_form_commerce_product_type_edit_form_alter($form,  $form_state, $form_id);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function apigee_m10n_add_credit_form_commerce_product_type_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\commerce_product\Entity\ProductTypeInterface $product_type */
  $default_value = (($product_type = $form_state->getFormObject()->getEntity())
    && $product_type->getThirdPartySetting('apigee_m10n_add_credit', 'apigee_m10n_enable_add_credit')
  ) ? TRUE : FALSE;

  // Add an option to allow enabling Apigee add credit for a product type.
  $form['apigee_m10n_enable_add_credit'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable <em>Apigee Monetization Add Credit</em> for this product type.'),
    '#default_value' => $default_value,
  ];
  // Add our own callback so we can save the add_credit enabled setting.
  array_splice($form["actions"]["submit"]["#submit"], -1, 0, 'apigee_m10n_add_credit_form_commerce_product_type_submit');
}

/**
 * Add a third party setting to the product type to flag whether or not this
 * product type is should be used as an apigee to up product.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function apigee_m10n_add_credit_form_commerce_product_type_submit(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\commerce_product\Entity\ProductTypeInterface $product_type */
  if (($product_type = $form_state->getFormObject()->getEntity())) {
    // Save the enabled setting to third party settings.
    $product_type->setThirdPartySetting(
      'apigee_m10n_add_credit',
      'apigee_m10n_enable_add_credit',
      $form_state->getValue('apigee_m10n_enable_add_credit')
    );
  }
}
