<?php

/**
 * @file
 * Copyright 2018 Google Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_mail().
 */
function apigee_m10n_add_credit_mail($key, &$message, $params) {
  apigee_m10n_add_credit_service()->mail($key, $message, $params);
}

/**
 * Implements hook_ENTITY_TYPE_create().
 */
function apigee_m10n_add_credit_commerce_order_item_create(EntityInterface $entity) {
  apigee_m10n_add_credit_service()->commerceOrderItemCreate($entity);
}

/**
 * Implements hook_entity_base_field_info().
 */
function apigee_m10n_add_credit_entity_base_field_info(EntityTypeInterface $entity_type) {
  return apigee_m10n_add_credit_service()->entityBaseFieldInfo($entity_type);
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function apigee_m10n_add_credit_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  return apigee_m10n_add_credit_service()->entityBundleFieldInfo($entity_type, $bundle, $base_field_definitions);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function apigee_m10n_add_credit_form_commerce_product_type_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  apigee_m10n_add_credit_service()->formCommerceProductTypeEditFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function apigee_m10n_add_credit_form_commerce_product_type_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  apigee_m10n_add_credit_service()->formCommerceProductTypeEditFormAlter($form, $form_state, $form_id);
}

/**
 * Helper to get the `apigee_m10n.add_credit` service.
 *
 * @return \Drupal\apigee_m10n_add_credit\AddCreditServiceInterface
 *   The `apigee_m10n.add_credit` service.
 */
function apigee_m10n_add_credit_service() {
  // Use static caching for performance.
  static $service;
  $service = $service ?: \Drupal::service('apigee_m10n.add_credit');

  return $service;
}
